#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [ "$COMMIT_SOURCE" = "message" ] || [ "$COMMIT_SOURCE" = "commit" ]; then
  exit 0
fi

# shellcheck disable=SC2015
exec < /dev/tty && node_modules/.bin/git-cz --hook --disable-emoji || true
